require("mani.options")
require("mani.keymaps")
require("mani.plugins")
require("mani.colorscheme")
require("mani.telescope")
require("mani.treesitter")
require("mani.harpoon")
require("mani.undotree")
require("mani.fugitive")
require("mani.lsp")
--require("mani.autopairs")

