require("mani.options")
require("mani.keymaps")
require("mani.plugins")
require("mani.telescope")
require("mani.treesitter")
require("mani.harpoon")
require("mani.undotree")
require("mani.fugitive")
require("mani.lsp")
require("mani.mason")
require("mani.dap")
require("mani.colorscheme")
-- require("mani.neoformat")
-- require("mani.statusBar")
require("mani.startup")
-- require("mani.neural")
require("mani.cmp")
require("mani.prettier")
-- require("mani.nvimide")

--require("mani.autopairs")

