require("mani.plugins_config.cmp")
require("mani.plugins_config.colorscheme")
require("mani.plugins_config.dap")
require("mani.plugins_config.gitsigns")
require("mani.plugins_config.harpoon")
require("mani.plugins_config.lsp")
require("mani.plugins_config.lualine")
require("mani.plugins_config.nvimTree")
require("mani.plugins_config.nullls")
-- require("mani.plugins_config.prettier")
require("mani.plugins_config.telescope")
require("mani.plugins_config.treesitter")
-- require("nvimide")
